### ISSUE TITLE
Better cache lock

### ISSUE THREAD

**Issue by edsko** [haskell/hackage-security#125]
Currently we create a directory `hackage-security-lock` in order to lock the cache; however, if the user interrupts the program (CTRL-C twice, for instance), we won't get a chance to remove this lock again and any subsequent attempts to check for updates will fail until the directory is manually removed.

A stop-gap measure would be to add a flag to ignore an existing lock, or ignore it automatically if the existing lock is older than a certain threshold; a proper solution would be to use some proper file locking but I don't know how to do that in a platform independent way.

**Comment by snoyberg** [comment]
This should be fixed by #203, with the caveat of #205. In other words, I think #205 supersedes this issue.

**Comment by dcoutts** [comment]
Agreed. Ta.
