### ISSUE TITLE
Write blog posts about having security in the official release of cabal

### ISSUE THREAD

**Issue by edsko** [haskell/hackage-security#147]
... and mention that enabling security is also a way of enabling mirroring.

(If the `nix` stuff makes it in before the next release, that obviously deserves a blog post as well.)

**Comment by hvr** [comment]
> (If the `nix` stuff makes it in before the next release, that obviously deserves a blog post as well.)

See haskell/cabal#3316 for that :-)

**Comment by hvr** [comment]
I think this one is the closest we got to address this issue:

https://www.well-typed.com/blog/2016/09/hackage-reliability-via-mirroring/
