### ISSUE TITLE
hackage-repo-tool needs documentation

### ISSUE THREAD

**Issue by ezyang** [haskell/hackage-security#173]
Things I'd like to see:

* A README, explaining what the tool might be used for, and some simple sample transcripts of interacting with a secure package repository using the tool. How many commands do I have to run before I get something that Cabal can understand
* Description of what each command does when I feed it `--help`. In particular, what does it mean to "bootstrap" a local repository? Does "create-keys" generate private keys?

**Comment by ezyang** [comment]
A good start: convert this blog post into the README: https://www.well-typed.com/blog/2015/07/hackage-security-alpha/ (but rename the executable.)

**Comment by hvr** [comment]
The README would be highly desirable displayed on Hackage, as the [cabal manual already links to](http://cabal.readthedocs.io/en/latest/installing-packages.html?highlight=hackage-repo-tool#secure-local-repositories) http://hackage.haskell.org/package/hackage-repo-tool
