### ISSUE TITLE
hackage-repo-tool bounds update

### ISSUE THREAD

**Issue by ezyang** [haskell/hackage-security#185]
Please make a new release of hackage-repo-tool and/or update the bounds on directory in the released version.

**Comment by hvr** [comment]
@ezyang how should the bounds be updated exactly? If you tell me, I can revise them on Hackage.

**Comment by ezyang** [comment]
Bump from 1.3 to 1.4; from this commit https://github.com/haskell/hackage-security/commit/2e8821eba6170f98109f9c344a880e9a880303bf

**Comment by hvr** [comment]
oh ... now I remember; I still need to code-review the `directory-1.4` relaxation which I merged to master... :-/
