### ISSUE TITLE
Aborting update can leave lock file

### ISSUE THREAD

**Issue by mgsloan** [haskell/hackage-security#186]
I'm having a hard time reproducing the issue, but see this stack issue: https://github.com/commercialhaskell/stack/issues/3055

Seems like it's possible to leave the lock file if an async exception is thrown in the middle of updating (in this case via ctrl-C

**Comment by ezyang** [comment]
I commented on the upstream for more clarification.

**Comment by ezyang** [comment]
Based on discussion in downstream, there is nothing we can do; this situation can occur if you C-c a process twice.

**Comment by chris-martin** [comment]
Can't we show a better error message, though, including remediation instructions? Am I supposed to manually delete `~/.stack/indices/Hackage/hackage-security-lock` now?
