### ISSUE TITLE
Expected correlation between .cabal and package.json files

### ISSUE THREAD

**Issue by snoyberg** [haskell/hackage-security#189]
I wanted to check on what the expected behavior in the 01-index.tar file is regarding package.json files. I would have expected that, regardless of the number of cabal file revisions, there would only ever be a single `package.json` file per package identifier (name/version combo). However, it appears on actual analysis that there are multiple such package.json files. A few questions:

* Am I correct in believing that the invariant should hold that each of these files has identical content? If not, under what circumstances could the metadata of a package tarball change over time?
* Is the current behavior to have a new package.json for each cabal file revision?

__EDIT__ Relevant part of the Stack code base: https://github.com/commercialhaskell/stack/pull/3275/commits/97ecd08acba28d6b56f41498a432d8ad8ed7d65d#diff-38ed43385886ae15c1d59bd461032ca1R168

**Comment by edsko** [comment]
Someone who has worked on this more recently than me may correct me, but IIRC, we do add a `package.json` for every revision, primarily to prepare for author signing, where revisions should be signed and hence listed in the `package.json` file.

**Comment by snoyberg** [comment]
Is it fair to check that the tarball size and hashes are consistent between two successive `package.json` files?

**Comment by edsko** [comment]
Yes, I think that should be fair.

**Comment by snoyberg** [comment]
OK, thanks. I've added an explicit test for this, which hopefully will never fire :)

I appreciate the quick responses.

**Comment by edsko** [comment]
@snoyberg so I was reminded that actually we changed this behaviour; the additional package.json files were created initially but not in later versions; see https://github.com/haskell/hackage-server/pull/469 . However, what I said above, I think, is still correct, that _if_ we adopt author signing then we will need to start adding more package.json files again (with the signed hash of the new `.cabal` file). When we do, your check (that the tarball size and hash haven't changed) should still be valid.
