### ISSUE TITLE
Package on Hackage isn't updated to revision changes.

### ISSUE THREAD

**Issue by arrowd** [haskell/hackage-security#190]
The .cabal file from https://hackage.haskell.org/package/hackage-security has `directory < 1.4` dependency, but downloaded archive has `directory < 1.3`. All revision updates seem to be missing. Not sure if it is package's problem or Hackage one.

**Comment by hvr** [comment]
Are you saying that https://hackage.haskell.org/package/hackage-security-0.5.2.2/hackage-security-0.5.2.2.tar.gz doesn't contain any revisions?

**Comment by hvr** [comment]
I just wanted to be sure what you were referring to; so yes, that's not a bug, but by design. We never mutate the source .tar.gz, instead the revised `.cabal` files are stored separately.

**Comment by arrowd** [comment]
Well, that's... Ok, I'd restrain from commenting. Thanks for you info.
