### ISSUE TITLE
Update .cabal metadata

### ISSUE THREAD

**Issue by edsko** [haskell/hackage-security#204]
The cabal file currently lists https://github.com/well-typed/hackage-security as the repo and bugtracker, but it has been moved to https://github.com/haskell/hackage-security . Additionally, it lists myself as the maintainer, but I'm not :) I don't know who is the maintainer though?

**Comment by hvr** [comment]
Well, it'd make sense to have it be aligned w/ cabal & hackage dev, as it's tightly entangled with those two, maybe a bit more w/ hackage than w/ cabal.

**Comment by hvr** [comment]
@edsko also note I updated the urls already early on via https://github.com/haskell/hackage-security/commit/4540e30f946d977930b8081f2a9900c207161aca

**Comment by 23Skidoo** [comment]
We can put `cabal-devel@haskell.org` into the "maintainer" field, like we do for `lib:Cabal` and `cabal-install`.

**Comment by Mikolaj** [comment]
I see this is fixed now. Closing.
