### ISSUE TITLE
ghc 8.4.1 support?

### ISSUE THREAD

**Issue by peti** [haskell/hackage-security#211]
hackage-security-0.5.2.2 specifies a `base >=4.5 && <4.11` constraint that prevents building the package with GHC 8.4.1. Would it be possible to lift that restriction?

**Comment by hvr** [comment]
No (otherwise I would have already) :-)

As I wrote in another issue, a new release will happen very soon; ETA in the next 72 hours

**Comment by tuncer** [comment]
Is there a new ETA?

**Comment by hvr** [comment]
This was actually already resolved via https://hackage.haskell.org/package/hackage-security-0.5.3.0
