### ISSUE TITLE
new release of hackage-security-HTTP

### ISSUE THREAD

**Issue by gbaz** [haskell/hackage-security#246]
thanks to https://github.com/haskell/hackage-security/commit/70aacb66e3deecd6fc8e450ca779b2c32f9ab18a the current release doesn't build against the current hackage-security, sigh...

**Comment by gbaz** [comment]
cc @hvr

**Comment by hvr** [comment]
resolved via https://hackage.haskell.org/package/hackage-security-HTTP-0.1.1.1
