### ISSUE TITLE
support ghc-9.0: base-4.15 and template-haskell-2.17

### ISSUE THREAD

**Issue by juhp** [haskell/hackage-security#253]
Just a ticket to track support for ghc-9.0

base-4.15.0.0 ([changelog](http://hackage.haskell.org/package/base-4.15.0.0/changelog)) is out of bounds for:
- [x] hackage-security-0.6.0.1 (>=4.5 && < 4.15). GHC 9 bounds issues, Grandfathered dependencies. @haskell. Used by: library

template-haskell-2.17.0.0 ([changelog](http://hackage.haskell.org/package/template-haskell-2.17.0.0/changelog)) is out of bounds for:
- [x] hackage-security-0.6.0.1 (>=2.7 && < 2.17). GHC 9 bounds issues, Grandfathered dependencies. @haskell. Used by: library

**Comment by Mikolaj** [comment]
I think this fixed now on master branch and I'm going to release RSN. Could you check the current codebase works for you and nothing extremely urgent is missing? Thank you!

**Comment by juhp** [comment]
So I opened thoughtpolice/hs-ed25519#30 ...

**Comment by juhp** [comment]
That one is already fixed now

**Comment by juhp** [comment]
And now I can build cabal-file with your repo

**Comment by Mikolaj** [comment]
\o/

**Comment by juhp** [comment]
Of course cabal-install can't build with ghc9 yet...

**Comment by Mikolaj** [comment]
Actually it should, soon, once this PR is merged: https://github.com/haskell/cabal/pull/7907
