### ISSUE TITLE
Remove the >= 8.2 workaround once Cabal > 3.8.1.0 is released

### ISSUE THREAD

**Issue by Mikolaj** [haskell/hackage-security#282]
The `&& impl(ghc >= 8.2)` workaround can then be removed, because the underlying problem is fixed on master and 3.8 branch. Actually, it's also worked around as a Cabal-syntax revision on Hackage (https://github.com/haskell/cabal/issues/8371), but I guess it's safer to wait for the permanent fix.

**Comment by juhp** [comment]
(Btw/tangentially cabal-install-3.6.2.0 fails to build when hackage-security pulls in Cabal-syntax)

**Comment by Mikolaj** [comment]
@juhp: isn't this fixed in hackage-security 0.6.2.2?

**Comment by Mikolaj** [comment]
Huh, it probably isn't --- I only fixed this for very old GHCs and for the hackage-security test suite itself. I'm afraid that's a case of https://github.com/haskell/cabal/issues/8370 and it can be worked around similarly as for hackage-security test suite in https://github.com/haskell/hackage-security/pull/281. 

That would be embarrassing. We'd need to fix old versions of cabal due to regressions in a new version.

**Comment by andreasabel** [comment]
We dropped GHC 8.2, so I guess this is resolved.
