### ISSUE TITLE
Release Hackage revision for `hackage-security-HTTP`

### ISSUE THREAD

**Issue by eddiejessup** [haskell/hackage-security#286]
I see that the versions have been bumped for a bunch of `hackage-security-*` packages, including `hackage-security-HTTP`, in [this PR](https://github.com/haskell/hackage-security/pull/284).

I also see that [hackage-security](https://hackage.haskell.org/package/hackage-security) has a [Hackage revision](https://hackage.haskell.org/package/hackage-security) with the new bounds.

But I don't see an equivalent revision for [hackage-security-HTTP](https://hackage.haskell.org/package/hackage-security-HTTP); would this be possible? I see that @Mikolaj did the revisions, but they aren't a maintainer of hackage-security-HTTP according to hackage metadata, so maybe someone else needs to do that (maintainers [here](https://hackage.haskell.org/package/hackage-security-HTTP/maintainers/))

**Comment by andreasabel** [comment]
I pushed a revision of the `base` and `HTTP` bounds to Hackage, so now all bounds should be up to date on Hackage.

**Comment by eddiejessup** [comment]
Yeah lgtm, thanks! Happy to close this
